[build]
  command = "yarn run build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "8.9.0"


# do a lighter build on the branches
[context.branch-deploy]
  command = "yarn run build"

[context.to-11ty]
  # environment = { NODE_ENV = "8.9.0" }
  command = "npm run build"

[[headers]]

 for = "/*"
 [headers.values]
   X-Frame-Options = "DENY"
   X-XSS-Protection = "1; mode=block"
   X-Content-Type-Options = "nosniff"
   Referrer-Policy= "no-referrer-when-downgrade"


# social media card assets
[[redirects]]
  from = "/card-image/:path"
  to = "https://hawksworx-cards.netlify.com/card/www-hawksworx-com:path"
  status = 302


# Simplify requests for my headshots
[[redirects]]
  from = "/philhawksworth-*"
  to = "/images/philhawksworth-:splat"

# Look after the old use of journal in urls



# 404s
[[redirects]]
  from = "*"
  to = "/404"
  status = 404
